swagger: '2.0'
info:
  title: Test for HTML Injection
  description: <ins>test</ins>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
