swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "1.0.0"
  title: <u>HTML Injection test</u>
  description: <u>Test Descripton</u>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
