swagger: '2.0'
info:
  title: Testing Injection
  description: This is a bold text **Bold Text**
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
